### ISSUE TITLE
data_cls.BertDataBunch has no "save" method

### ISSUE THREAD

**Issue by enzoampil** [kaushaltrivedi/fast-bert#109]
There's no ```save``` method in ```data_cls.BertDataBunch``` which makes it difficult to save databunches for later. This is strange since this should be a built in method for fastai databunches. Would we maybe want ```BertDataBunch``` to inherit from [fastai's](https://github.com/fastai/fastai/blob/master/fastai/basic_data.py#L149) ```DataBunch``` class?

For now I'm utilizing the cache files being generated, storing them in a separate directory, and bringing them back to the ```cache``` directory once I want to reuse them.

**Comment by utterworks** [comment]
Cache does the same work as save. Unless I am missing something.

**Comment by enzoampil** [comment]
It does in a sense but the difference is in the use case. The cache allows my current session to reuse the last cached ```DataBunch``` but an explicit ```save``` method allows me to save the the ```DataBunch``` object in a specific path and with a specific name (versioning).

The simple caching doesn't allow the above easily.
