### ISSUE TITLE
Is it possible to get the label probablities before final prediction for multi-label classification?

### ISSUE THREAD

**Issue by ehsan-soe** [kaushaltrivedi/fast-bert#121]
Hi,

Thanks for the nice resource.
I wonder if it is possible to get the label probabilities before final prediction for multi-label classification?
I mean a vector with a dimension of number of labels which contains probability of each label.

**Comment by Naawel** [comment]
Hello,

I'm encountering the same issue. I'd like to know how you managed it please.
