### ISSUE TITLE
Pipeline?

### ISSUE THREAD

**Issue by zampierimatteo91** [kaushaltrivedi/fast-bert#127]
Hello,

Thank you very much for this library.

One silly question: which pipeline should we follow? Are the snippets provided in the main README enough to be inserted in a simple script to run first a fine-tuning and then a prediction?
Or is there more to it?

Thank you again and sorry for the stupidity of the question.

**Comment by kaushaltrivedi** [comment]
Just check out sample notebooks they should help.
