### ISSUE TITLE
Cannot import ConstantLRSchedule

### ISSUE THREAD

**Issue by zampierimatteo91** [kaushaltrivedi/fast-bert#129]
Hello everybody,
I am trying to run a classification on Google Colab, but the code fails at import time:
```
Traceback (most recent call last):
  File "multi_classification.py", line 10, in <module>
    from fast_bert.data import BertDataBunch
  File "/content/drive/My Drive/fast-bert/fast_bert/__init__.py", line 5, in <module>
    from .learner_cls import BertLearner
  File "/content/drive/My Drive/fast-bert/fast_bert/learner_cls.py", line 3, in <module>
    from .learner_util import Learner
  File "/content/drive/My Drive/fast-bert/fast_bert/learner_util.py", line 4, in <module>
    from transformers import (ConstantLRSchedule,
ImportError: cannot import name 'ConstantLRSchedule'
```

I pip-installed transformers and all the dependencies; do you know what could the problem be?
Thanks

*EDIT* : I am looking at my local `transformers` repository, and in `optimization.py` I see:

```import logging
import math

import torch
from torch.optim import Optimizer
from torch.optim.lr_scheduler import LambdaLR

logger = logging.getLogger(__name__)


def get_constant_schedule(optimizer, last_epoch=-1):
    """ Create a schedule with a constant learning rate.
    """
    return LambdaLR(optimizer, lambda _: 1, last_epoch=last_epoch)


def get_constant_schedule_with_warmup(optimizer, num_warmup_steps, last_epoch=-1):
    """ Create a schedule with a constant learning rate preceded by a warmup
    period during which the learning rate increases linearly between 0 and 1.
    """
    def lr_lambda(current_step):
        if current_step < num_warmup_steps:
            return float(current_step) / float(max(1.0, num_warmup_steps))
        return 1.

    return LambdaLR(optimizer, lr_lambda, last_epoch=last_epoch)


def get_linear_schedule_with_warmup(optimizer, num_warmup_steps, num_training_steps, last_epoch=-1):
    """ Create a schedule with a learning rate that decreases linearly after
    linearly increasing during a warmup period.
    """
    def lr_lambda(current_step):
        if current_step < num_warmup_steps:
            return float(current_step) / float(max(1, num_warmup_steps))
        return max(0.0, float(num_training_steps - current_step) / float(max(1, num_training_steps - num_warmup_steps)))

    return LambdaLR(optimizer, lr_lambda, last_epoch)

```
It might be a change in naming?
In Colab transformers is 2.2.0.

**EDIT 2**: I just checked the documentation of both transformers==2.2.0 and transformers==2.0.0. Apparently the latest has implemented functions instead of classes, so you should use `get_constant_schedule()` instead of `ConstantLRSchedule()`.

I have downgraded transformers to 2.0.0 in my Colab.
No error on that import, I just have an error on importing `MultiLabelTextProcessor`.

**Comment by 008karan** [comment]
> Hello everybody,
> I am trying to run a classification on Google Colab, but the code fails at import time:
> 
> ```
> Traceback (most recent call last):
>   File "multi_classification.py", line 10, in <module>
>     from fast_bert.data import BertDataBunch
>   File "/content/drive/My Drive/fast-bert/fast_bert/__init__.py", line 5, in <module>
>     from .learner_cls import BertLearner
>   File "/content/drive/My Drive/fast-bert/fast_bert/learner_cls.py", line 3, in <module>
>     from .learner_util import Learner
>   File "/content/drive/My Drive/fast-bert/fast_bert/learner_util.py", line 4, in <module>
>     from transformers import (ConstantLRSchedule,
> ImportError: cannot import name 'ConstantLRSchedule'
> ```
> 
> I pip-installed transformers and all the dependencies; do you know what could the problem be?
> Thanks
> 
> _EDIT_ : I am looking at my local `transformers` repository, and in `optimization.py` I see:
> 
> ```
> import math
> 
> import torch
> from torch.optim import Optimizer
> from torch.optim.lr_scheduler import LambdaLR
> 
> logger = logging.getLogger(__name__)
> 
> 
> def get_constant_schedule(optimizer, last_epoch=-1):
>     """ Create a schedule with a constant learning rate.
>     """
>     return LambdaLR(optimizer, lambda _: 1, last_epoch=last_epoch)
> 
> 
> def get_constant_schedule_with_warmup(optimizer, num_warmup_steps, last_epoch=-1):
>     """ Create a schedule with a constant learning rate preceded by a warmup
>     period during which the learning rate increases linearly between 0 and 1.
>     """
>     def lr_lambda(current_step):
>         if current_step < num_warmup_steps:
>             return float(current_step) / float(max(1.0, num_warmup_steps))
>         return 1.
> 
>     return LambdaLR(optimizer, lr_lambda, last_epoch=last_epoch)
> 
> 
> def get_linear_schedule_with_warmup(optimizer, num_warmup_steps, num_training_steps, last_epoch=-1):
>     """ Create a schedule with a learning rate that decreases linearly after
>     linearly increasing during a warmup period.
>     """
>     def lr_lambda(current_step):
>         if current_step < num_warmup_steps:
>             return float(current_step) / float(max(1, num_warmup_steps))
>         return max(0.0, float(num_training_steps - current_step) / float(max(1, num_training_steps - num_warmup_steps)))
> 
>     return LambdaLR(optimizer, lr_lambda, last_epoch)
> ```
> 
> It might be a change in naming?
> In Colab transformers is 2.2.0.
> 
> **EDIT 2**: I just checked the documentation of both transformers==2.2.0 and transformers==2.0.0. Apparently the latest has implemented functions instead of classes, so you should use `get_constant_schedule()` instead of `ConstantLRSchedule()`.
> 
> I have downgraded transformers to 2.0.0 in my Colab.
> No error on that import, I just have an error on importing `MultiLabelTextProcessor`.

Though it worked yesterday but having the same issue since the evening 
Please suggest something
it's urgent

**Comment by zampierimatteo91** [comment]
Now I can suggest to downgrade transformers to version 2.0.0
pip install transformers==2.0.0

Im not with my laptop right now, but after that it worked. I removed the other import I was doing (the MultiLabelTextProcessor) as it was not necessary. My code then was giving error on my data files, but I think it’s how I formatted the data and will look later on that.

**Comment by kaushaltrivedi** [comment]
This has been fixed in latest release.
