### ISSUE TITLE
Error with multi_label=False in BertDataBunch 

### ISSUE THREAD

**Issue by kazyka** [kaushaltrivedi/fast-bert#14]
I am trying to detect lies in text, so it can either be the person telling the truth or a lie.

So this is not a multi_label problem, and therefore my BertDataBunch is looking like

```

databunch = BertDataBunch(args['data_dir'], LABEL_PATH, tokenizer, train_file='train.csv', val_file='val.csv',
                          test_data='test.csv',
                          text_col="content", label_col=label_cols,
                          bs=args['train_batch_size'], maxlen=args['max_seq_length'], 
                          multi_gpu=multi_gpu, multi_label=False)

```

However I am then getting a keyerror

`'lie    0\nName: 0, dtype: object'`

**Comment by Pawel-Kranzberg** [comment]
Did you specify correctly the LABEL_PATH?
Does your label_file (the actual .csv file that the LABEL_PATH leads to) has the contents like this (no header, no index)?
```
lie
truth
```
Does your label_col contain the name of the target column?

**Comment by tracyphamcse** [comment]
I also got an error with **multi_label=False**

`databunch = BertDataBunch(DATA_PATH, LABEL_PATH, tokenizer, 
                          train_file='train.csv', label_file='labels.csv',
                          bs=args['train_batch_size'], maxlen=args['max_seq_length'], 
                          text_col='text', label_col='label',
                          multi_gpu=False, multi_label=False)`

_train.csv_ has two columns: _text_ and _label_. label is column with value 0 or 1.
_labels.csv_ has two rows
`
label1
label2
`
The error is: 
`---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-9-f95a25df587e> in <module>
      3                           bs=args['train_batch_size'], maxlen=args['max_seq_length'],
      4                           text_col='text', label_col='label',
----> 5                           multi_gpu=False, multi_label=False)

~/Applications/anaconda3/envs/fastbert/lib/python3.6/site-packages/fast_bert/data.py in __init__(self, data_dir, label_dir, tokenizer, train_file, val_file, test_data, label_file, text_col, label_col, bs, maxlen, multi_gpu, multi_label)
    352                 train_file, text_col=text_col, label_col=label_col)
    353             train_features = convert_examples_to_features(train_examples, label_list=self.labels,
--> 354                                                           tokenizer=tokenizer, max_seq_length=maxlen)
    355 
    356             all_input_ids = torch.tensor(

~/Applications/anaconda3/envs/fastbert/lib/python3.6/site-packages/fast_bert/data.py in convert_examples_to_features(examples, label_list, max_seq_length, tokenizer)
    117         else:
    118             if example.label != None:
--> 119                 label_id = label_map[example.label]
    120             else:
    121                 label_id = ''

KeyError: '1'
`
I have looked at the file fast-bert/data.py and found that the label in **InputExample** is **str**
`return list(df.apply(lambda row: InputExample(guid=row.index, text_a=row[text_col], label=str(row[label_col])), axis=1))`
while the key in **label_map** is **int**
`label_map = {label: i for i, label in enumerate(label_list)}`

**Comment by titu1992** [comment]
Even I am getting the below error while initiating the databunch. I have used the SampleData provided by the author in the github and trying to reproduce the toxic_multilabel.pynb
KeyError: 'toxic            0\nsevere_toxic     0\nobscene          0\nthreat           0\ninsult           0\nidentity_hate    0\nName: 0, dtype: object'

What is expected here? should my train.cv have a lable column as well? consisting of the label_col values?

**Comment by titu1992** [comment]
Solved the error, as the multi_label value was set to false. setting it to true solved the error.

**Comment by shyamrallapalli** [comment]
I had this error for multi_class data when ```multi_label=False``` does that mean
```python
multi_label=True
```
is needed for both multi_label and multi_class
Just a bit misled by the naming here.
Could multi_class be worked out if `label_col` is a list?, just a thought
