### ISSUE TITLE
Missing module import in data_lm.py

### ISSUE THREAD

**Issue by chunkhai96** [kaushaltrivedi/fast-bert#143]
There is a issue which returning error when using clear_cache on creating data bunch for finetuning language model.
https://github.com/kaushaltrivedi/fast-bert/blob/12c0dbcef46d6c1e5acf46c281659047460e67db/fast_bert/data_lm.py#L197
 Please add `import shutil` in data_lm.py.

**Comment by kaushaltrivedi** [comment]
fixed
