### ISSUE TITLE
KeyError: 'distilroberta-base' | UnboundLocalError: local variable 'file_path' referenced before assignment

### ISSUE THREAD

**Issue by emtropyml** [kaushaltrivedi/fast-bert#147]
Step 23/23 : RUN python download_pretrained_models.py --location_dir ./pretraine                                                                                        d_models/ --models bert-base-uncased roberta-base distilbert-base-uncased distil                                                                                        roberta-base
 ---> Running in ea0f4907e7f3
Namespace(location_dir='./pretrained_models/', models=['bert-base-uncased', 'rob                                                                                        erta-base', 'distilbert-base-uncased', 'distilroberta-base'])
model name is bert-base-uncased
location is pretrained_models/bert-base-uncased
file path is https://s3.amazonaws.com/models.huggingface.co/bert/bert-base-uncas                                                                                        ed-vocab.txt
100%|██████████| 231508/231508 [00:00<00:00, 23495328.36B/s]
https://s3.amazonaws.com/models.huggingface.co/bert/bert-base-uncased-pytorch_mo                                                                                        del.bin
100%|█████████▉| 440048640/440473133 [00:08<00:00, 52815268.67B/s]https://s3.ama                                                                                        zonaws.com/models.huggingface.co/bert/bert-base-uncased-config.json
100%|██████████| 440473133/440473133 [00:08<00:00, 50842146.41B/s]
  0%|          | 0/313 [00:00<?, ?B/s]model name is roberta-base
location is pretrained_models/roberta-base
100%|██████████| 313/313 [00:00<00:00, 235567.41B/s]
file path is https://s3.amazonaws.com/models.huggingface.co/bert/roberta-base-vo                                                                                        cab.json
100%|██████████| 898823/898823 [00:00<00:00, 35036913.95B/s]
https://s3.amazonaws.com/models.huggingface.co/bert/roberta-base-merges.txt
100%|██████████| 456318/456318 [00:00<00:00, 34051566.76B/s]
https://s3.amazonaws.com/models.huggingface.co/bert/roberta-base-pytorch_model.b                                                                                        in
100%|██████████| 501200538/501200538 [00:12<00:00, 41648047.00B/s]
https://s3.amazonaws.com/models.huggingface.co/bert/roberta-base-config.json
100%|██████████| 473/473 [00:00<00:00, 325337.13B/s]
model name is distilbert-base-uncased
location is pretrained_models/distilbert-base-uncased
file path is https://s3.amazonaws.com/models.huggingface.co/bert/bert-base-uncas                                                                                        ed-vocab.txt
100%|██████████| 231508/231508 [00:00<00:00, 31093372.52B/s]
https://s3.amazonaws.com/models.huggingface.co/bert/distilbert-base-uncased-pyto                                                                                        rch_model.bin
 99%|█████████▉| 265882624/267967963 [00:07<00:00, 53809389.38B/s]https://s3.ama                                                                                        zonaws.com/models.huggingface.co/bert/distilbert-base-uncased-config.json
100%|██████████| 267967963/267967963 [00:07<00:00, 35726735.77B/s]
100%|██████████| 492/492 [00:00<00:00, 315341.93B/s]
model name is distilroberta-base
location is pretrained_models/distilroberta-base
Traceback (most recent call last):
  File "download_pretrained_models.py", line 113, in download_pretrained_files
    file_path = PRETRAINED_VOCAB_FILES_MAP[model_name]
**KeyError: 'distilroberta-base'**

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "download_pretrained_models.py", line 203, in <module>
    main()
  File "download_pretrained_models.py", line 198, in main
    for item in args.models
  File "download_pretrained_models.py", line 198, in <listcomp>
    for item in args.models
  File "download_pretrained_models.py", line 130, in download_pretrained_files
    file_path, model_name
**UnboundLocalError: local variable 'file_path' referenced before assignment**
**The command '/bin/sh -c python download_pretrained_models.py --location_dir ./pr                                                                                        etrained_models/ --models bert-base-uncased roberta-base distilbert-base-uncased                                                                                         distilroberta-base' returned a non-zero code: 1**
Error response from daemon: No such image: fluent-sagemaker-fast-bert:1.0-gpu-py                                                                                        36
The push refers to repository [182918221797.dkr.ecr.us-east-1.amazonaws.com/flue                                                                                        nt-sagemaker-fast-bert]
An image does not exist locally with the tag: 182918221797.dkr.ecr.us-east-1.ama                                                                                        zonaws.com/fluent-sagemaker-fast-bert

**Comment by raiyani** [comment]
Any solution for this problem, @emtropyml ? I hit this one too... Thanks in advance!

**Comment by emtropyml** [comment]
I just removed "distilroberta-base" from the last line of the Dockerfile. But in case you want to use DistilRoBERTa, you'd have to make appropriate changes to the "fast-bert/container/bert/download_pretrained_models.py" file

**Comment by raiyani** [comment]
Thank you again, @emtropyml ! That worked too...

**Comment by kaushaltrivedi** [comment]
fixed

**Comment by emtropyml** [comment]
Thanks @kaushaltrivedi , would be good to add the new models to the DockerFile as well (referring to the last line `RUN python download_pretrained_models.py --location_dir ./pretrained_models/ --models` ...)
