### ISSUE TITLE
ModuleNotFoundError: No module named 'fastai'

### ISSUE THREAD

**Issue by emtropyml** [kaushaltrivedi/fast-bert#148]
2019-12-12 09:30:28 Starting - Starting the training job...
2019-12-12 09:30:29 Starting - Launching requested ML instances......
2019-12-12 09:31:43 Starting - Preparing the instances for training......
2019-12-12 09:32:55 Downloading - Downloading input data
2019-12-12 09:32:55 Training - Downloading the training image..............Traceback (most recent call last):
  File "/opt/ml/code/train", line 23, in <module>
    from fast_bert.data_cls import BertDataBunch
  File "/usr/local/lib/python3.7/dist-packages/fast_bert/__init__.py", line 5, in <module>
    from .learner_cls import BertLearner
  File "/usr/local/lib/python3.7/dist-packages/fast_bert/learner_cls.py", line 97, in <module>
    from fastai.torch_core import *
**ModuleNotFoundError: No module named 'fastai'**

2019-12-12 09:35:16 Uploading - Uploading generated training model
2019-12-12 09:35:16 Failed - Training job failed
---------------------------------------------------------------------------
UnexpectedStatusException                 Traceback (most recent call last)
<ipython-input-14-41efce4517f5> in <module>()
----> 1 estimator.fit(s3_input)

~/anaconda3/envs/python3/lib/python3.6/site-packages/sagemaker/estimator.py in fit(self, inputs, wait, logs, job_name, experiment_config)
    462         self.jobs.append(self.latest_training_job)
    463         if wait:
--> 464             self.latest_training_job.wait(logs=logs)
    465 
    466     def _compilation_job_name(self):

~/anaconda3/envs/python3/lib/python3.6/site-packages/sagemaker/estimator.py in wait(self, logs)
   1059         # If logs are requested, call logs_for_jobs.
   1060         if logs != "None":
-> 1061             self.sagemaker_session.logs_for_job(self.job_name, wait=True, log_type=logs)
   1062         else:
   1063             self.sagemaker_session.wait_for_job(self.job_name)

~/anaconda3/envs/python3/lib/python3.6/site-packages/sagemaker/session.py in logs_for_job(self, job_name, wait, poll, log_type)
   2972 
   2973         if wait:
-> 2974             self._check_job_status(job_name, description, "TrainingJobStatus")
   2975             if dot:
   2976                 print()

~/anaconda3/envs/python3/lib/python3.6/site-packages/sagemaker/session.py in _check_job_status(self, job, desc, status_key_name)
   2566                 ),
   2567                 allowed_statuses=["Completed", "Stopped"],
-> 2568                 actual_status=status,
   2569             )
   2570 

**UnexpectedStatusException: Error for Training job toxic-comments-2019-12-12-09-30-28-175: Failed. Reason: AlgorithmError: Exit Code: 1**

**Comment by raiyani** [comment]
I ran into the same issue, @emtropyml . Any luck? Thanks in advance!

**Comment by emtropyml** [comment]
You can add `RUN pip --no-cache-dir install fastai` to the Dockerfile, it should work then.

**Comment by kaushaltrivedi** [comment]
you should not need fastai anymore
