### ISSUE TITLE
NameError: name 'AdamW' is not defined

### ISSUE THREAD

**Issue by emtropyml** [kaushaltrivedi/fast-bert#149]
UnexpectedStatusException: Error for Training job toxic-comments-2019-12-12-11-10-04-490: Failed. Reason: AlgorithmError: Exception during training: name 'AdamW' is not defined
Traceback (most recent call last):
  File "/opt/ml/code/train", line 216, in train
    optimizer_type=hyperparameters["optimizer_type"],
  File "/usr/local/lib/python3.7/dist-packages/fast_bert/learner_cls.py", line 311, in fit
    optimizer = self.get_optimizer(lr, optimizer_type=optimizer_type)
  File "/usr/local/lib/python3.7/dist-packages/fast_bert/learner_util.py", line 90, in get_optimizer
    optimizer = AdamW(
**NameError: name 'AdamW' is not defined**

**Comment by kaushaltrivedi** [comment]
has been fixed in release 1.5.1

**Comment by M4MURARI** [comment]
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-1-fbc6885bf562> in <module>
     68 
     69 # Define optimizer
---> 70 optimizer = AdamW(model.parameters(), lr=2e-5, eps=1e-8)
     71 
     72 # Define a loss function

NameError: name 'AdamW' is not defined
