### ISSUE TITLE
from apex import amp issue in google collab

### ISSUE THREAD

**Issue by RwGrid** [kaushaltrivedi/fast-bert#166]
i am trying to implement ur library but i stumble there every time, i check requirements,tried different fixes but to no avail

**Comment by RwGrid** [comment]
i solved it, in google collab
run this first to install apex:
%%writefile setup.sh

git clone https://github.com/NVIDIA/apex
cd apex
pip install -v --no-cache-dir ./
then the next cell:
!sh setup.sh
last to solve apex: move the apex folder into a level similar to ur .py file(multilabel classification file) and put them in similar place by relocating the apex file
using : 
import shutil
shutil.move('/content/apex','/content/drive/My Drive/bertapex')

**Comment by trisongz** [comment]
Just in case anyone else runs across this issue - I've reported it to the Colab Team and there's a fix in the comments as well.

https://github.com/googlecolab/colabtools/issues/1106

```
## Check Cuda Location
!ls -al /usr/local/cuda
#This will occasionally show CUDA 10.0 as the syslinked CUDA version

## symlink proper CUDA
!sudo unlink /usr/local/cuda
!sudo ln -s /usr/local/cuda-10.1 /usr/local/cuda

## Install APEX
%cd /content
!git clone https://github.com/NVIDIA/apex
%cd /content/apex

!pip install -v --no-cache-dir --global-option="--pyprof" --global-option="--cpp_ext" --global-option="--cuda_ext" .
```
