### ISSUE TITLE
AttributeError: 'AlbertForMultiLabelSequenceClassification' object has no attribute 'roberta'

### ISSUE THREAD

**Issue by lingdoc** [kaushaltrivedi/fast-bert#172]
Trying to use Albert, successfully loaded data and tokenizer using term names from the HuggingFace tokenizer descriptions for Albert (https://huggingface.co/transformers/_modules/transformers/tokenization_albert.html). The `BertDataBunch()` call seems to run fine with `tokenizer='albert-base-v2', model_type='albert'`. Then I call:

```
learner = BertLearner.from_pretrained_model(
						databunch,
						pretrained_path='albert-base-v2',
						metrics=metrics,
						device=device_cuda,
						logger=logger,
						output_dir=OUTPUT_DIR,
						finetuned_wgts_path=None,
						warmup_steps=20,
						multi_gpu=False,
						is_fp16=True,
						multi_label=True,
						logging_steps=5)
```

Which seems to work fine. The attribute error happens when trying to train a model:

```
learner.fit(epochs=6,
			lr=6e-5,
			validate=True, 	# Evaluate the model after each epoch
			schedule_type="warmup_cosine",
			optimizer_type="lamb")
```

 In the `modeling.py` script it seems that `roberta()` gets called in both Albert and Camembert models.

**Comment by flappy007** [comment]
in modelling.py in AlbertForMultiLabelSequenceClassification change roberta to albert:
**outputs = self.albert(** 

and 

replace:

sequence_output = outputs[0]
logits = self.classifier(sequence_output)
outputs = (logits,) + outputs[2:]

to 

pooled_output = outputs[1]
pooled_output = self.dropout(pooled_output)
logits = self.classifier(pooled_output)
outputs = (logits,) + outputs[2:]

**Comment by lingdoc** [comment]
ok, I can now load the model! but now I'm getting a CUDA oom error in training... closing this issue since cloning the repo and editing the script fixed the attribute error.
