### ISSUE TITLE
NameError: name 'threshold' is not defined

### ISSUE THREAD

**Issue by sagol** [kaushaltrivedi/fast-bert#20]
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-5-332b4c5f921c> in <module>()
      8 from pytorch_pretrained_bert.tokenization import BertTokenizer
      9 
---> 10 from fast_bert.data import BertDataBunch
     11 from fast_bert.learner import BertLearner
     12 from fast_bert.metrics import accuracy, accuracy_thresh, fbeta, roc_auc

/opt/conda/lib/python3.6/site-packages/fast_bert/__init__.py in <module>()
      1 from .modeling import BertForMultiLabelSequenceClassification
      2 from .data import BertDataBunch, InputExample, InputFeatures, MultiLabelTextProcessor, convert_examples_to_features
----> 3 from .metrics import accuracy, accuracy_thresh, fbeta, roc_auc, accuracy_multilabel
      4 from .learner import BertLearner
      5 from .prediction import BertClassificationPredictor

/opt/conda/lib/python3.6/site-packages/fast_bert/metrics.py in <module>()
     54     return roc_auc["micro"]
     55 
---> 56 def Hamming_loss(y_pred:Tensor, y_true:Tensor, sigmoid:bool = True, thresh:float = threshold, sample_weight = None):
     57     if sigmoid: y_pred = y_pred.sigmoid()
     58     y_pred = (y_pred > thresh).float()

NameError: name 'threshold' is not defined

**Comment by Pawel-Kranzberg** [comment]
Yes, the fix is here https://github.com/kaushaltrivedi/fast-bert/pull/16

**Comment by Pawel-Kranzberg** [comment]
@sagol Please close this issue.
