### ISSUE TITLE
cannot import name 'ConstantLR'

### ISSUE THREAD

**Issue by bboczeng** [kaushaltrivedi/fast-bert#21]
When installing `fast_bert` after `pip install fast_bert`, i got this in `from fast_bert.learner import BertLearner`

**Comment by bboczeng** [comment]
`from pytorch_pretrained_bert.optimization import BertAdam, ConstantLR, WarmupCosineSchedule, WarmupConstantSchedule, WarmupLinearSchedule, WarmupCosineWithWarmupRestartsSchedule, WarmupCosineWithHardRestartsSchedule`

**Comment by adich23** [comment]
Faced the same problem, then I pytorch_pretrained_bert updated to 0.6.2 and it resolved.
