### ISSUE TITLE
The current BertClassificationPredictor has a bug in model_path parameter 

### ISSUE THREAD

**Issue by markovivl** [kaushaltrivedi/fast-bert#216]
The current BertClassificationPredictor has a bug in model_path parameter when it tries to create tokenizer from AutoTokenizer. It would be good to fix it but also let an option to provide a custom tokenizer.

**Comment by markovivl** [comment]
Mainly, the bug is that AutoTokenizer expects a str object, and is provided a PathIx object.

**Comment by aaronbriel** [comment]
Why are you passing it a Pathlx object instead of a str?

**Comment by markovivl** [comment]
You are right, it is probably my fault and not the library, but in my defense I was running the sample notebook when the error happened.

**Comment by aaronbriel** [comment]
No worries! The notebooks may indeed be in need of some attention.
