### ISSUE TITLE
Accuracy_multilabel function probably incorrect

### ISSUE THREAD

**Issue by 53X** [kaushaltrivedi/fast-bert#23]
Hi, 

```python3

def accuracy_multilabel(y_pred:Tensor, y_true:Tensor, sigmoid:bool=True):
    if sigmoid: y_pred = y_pred.sigmoid()
    outputs = np.argmax(y_pred, axis=1)
    real_vals = np.argmax(y_true, axis=1)
    return np.mean(outputs.numpy() == real_vals.numpy())

```

in [this](https://github.com/kaushaltrivedi/fast-bert/blob/4043fd3c91966807a5474a6afccc18538cea0fd5/fast_bert/metrics.py#L15-19) block.

This piece of code seems incorrect as the shape of `y_pred` and `y_true `is `(Batch_size, class_space)`.
Doing a `np.argmax` with `axis=1` returns a single class index value for each sample. 
This is what we do for **multi-class classification.** 

However in multi-class classification we don't normally use `sigmoid` on `y_pred`, although it is not wrong.

This function seems much like `accuracy_multiclass` rather than `accuracy_multilabel`

**Comment by kaushaltrivedi** [comment]
The idea behind this was to pick the accuracy of top predicted label.  You are right, accuracy_thresh is meant to be used for multi-label models.  This was more as an experiment.
