### ISSUE TITLE
Load the model on CPU instead of GPU

### ISSUE THREAD

**Issue by ahmedbahaaeldin** [kaushaltrivedi/fast-bert#25]
I cant load the model on CPU instead of GPU while trained on GPU. Can somebody tell me

**Comment by Pawel-Kranzberg** [comment]
@ahmedbahaaeldin  - could you provide more detail? I've loaded a GPU-trained model on CPU without errors. Still, it then works so slow, that it can make you consider using a GPU.

**Comment by kaushaltrivedi** [comment]
Sorry it will be too much trouble to support CPU training.  Once the mode ls trained it can definitely be hosted on a CPU based machine for inference.
