### ISSUE TITLE
Unsupported operand type(s) for /: 'str' and 'str'

### ISSUE THREAD

**Issue by miluki01** [kaushaltrivedi/fast-bert#33]
when I tried to run the example. I got the error:
```
databunch = BertDataBunch('./data/', './data/',
                          tokenizer='bert-base-uncased',
                          train_file='train.csv',
                          val_file='val.csv',
                          label_file='labels.csv',
                          text_col='text',
                          label_col='label',
                          batch_size_per_gpu=16,
                          max_seq_length=512,
                          multi_gpu=True,
                          multi_label=False,
                          model_type='bert',
                          no_cache=True)

```

--------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-2-dffcd4a29740> in <module>
     11                           multi_label=False,
     12                           model_type='bert',
---> 13                           no_cache=True)

/data/miniconda3/envs/pt/lib/python3.7/site-packages/fast_bert/data_cls.py in __init__(self, data_dir, label_dir, tokenizer, train_file, val_file, test_data, label_file, text_col, label_col, batch_size_per_gpu, max_seq_length, multi_gpu, multi_label, backend, model_type, logger, clear_cache, no_cache)
    288         self.tokenizer = tokenizer
    289         self.data_dir = data_dir
--> 290         self.cache_dir = data_dir/'cache'
    291         self.max_seq_length = max_seq_length
    292         self.batch_size_per_gpu = batch_size_per_gpu

TypeError: unsupported operand type(s) for /: 'str' and 'str'
Could you help me to deal with that?

**Comment by kaushaltrivedi** [comment]
Convert ‘/data/‘ into a Path object. The DataBunch expects a Path object. 

from pathlib import Path
DATA_PATH = Path(‘./data/‘)

**Comment by miluki01** [comment]
Hi @kaushaltrivedi ,
How about the LABEL_PATH, is that path to label_file?

**Comment by kaushaltrivedi** [comment]
Yes

**Comment by miluki01** [comment]
I got it!
Thank you a lot
