### ISSUE TITLE
Incomplete class Learner(object)

### ISSUE THREAD

**Issue by vondersam** [kaushaltrivedi/fast-bert#35]
Hi @kaushaltrivedi. Thanks so much for creating this library, it's great. 

I was using it a few days ago and it worked well. But now I'm getting an import error from `fast_bert/learner.py`. I think it's due to a incomplete `class Learner(object):`. Complete message below:

`File "/usr/local/lib/python3.6/dist-packages/fast_bert/learner.py", line 61
    class BertLearner(object):
        ^
IndentationError: expected an indented block`

**Comment by kaushaltrivedi** [comment]
Hello with the new refactoring for library, use learner_cls instead of learner.  Also use data_cls instead of data for BertDataBunch

**Comment by vondersam** [comment]
That worked, thank you!
