### ISSUE TITLE
Torch not compiled with Cuda enabled

### ISSUE THREAD

**Issue by Ryang20718** [kaushaltrivedi/fast-bert#36]
from fast_bert.learner_cls import BertLearner
from fast_bert.metrics import accuracy
import logging

logger = logging.getLogger()
device_cuda = torch.device('cpu') #torch.device("cuda")
metrics = [{'name': 'accuracy', 'function': accuracy}]

learner = BertLearner.from_pretrained_model(
    databunch,
    pretrained_path='bert-base-uncased',
    metrics=metrics,
    device=device_cuda,
    logger=logger,
    output_dir=MODEL_PATH,
    finetuned_wgts_path=None,
    warmup_steps=500,
    multi_gpu=multi_gpu,
    is_fp16=True,
    multi_label=False,
    logging_steps=50)

---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-57-a5a67feeebf8> in <module>
     19     is_fp16=True,
     20     multi_label=False,
---> 21     logging_steps=50)

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/fast_bert/learner_cls.py in from_pretrained_model(dataBunch, pretrained_path, output_dir, metrics, device, logger, finetuned_wgts_path, multi_gpu, is_fp16, loss_scale, warmup_steps, fp16_opt_level, grad_accumulation_steps, multi_label, max_grad_norm, adam_epsilon, logging_steps)
     67             model = model_class[0].from_pretrained(pretrained_path, config=config)
     68 
---> 69         device_id = torch.cuda.current_device()
     70         model.to(device)
     71 

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/torch/cuda/__init__.py in current_device()
    349 def current_device():
    350     r"""Returns the index of a currently selected device."""
--> 351     _lazy_init()
    352     return torch._C._cuda_getDevice()
    353 

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/torch/cuda/__init__.py in _lazy_init()
    160         raise RuntimeError(
    161             "Cannot re-initialize CUDA in forked subprocess. " + msg)
--> 162     _check_driver()
    163     torch._C._cuda_init()
    164     _cudart = _load_cudart()

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/torch/cuda/__init__.py in _check_driver()
     73 def _check_driver():
     74     if not hasattr(torch._C, '_cuda_isDriverSufficient'):
---> 75         raise AssertionError("Torch not compiled with CUDA enabled")
     76     if not torch._C._cuda_isDriverSufficient():
     77         if torch._C._cuda_getDriverVersion() == 0:

AssertionError: Torch not compiled with CUDA enabled

I can't run a model on os X and I was wondering if I could train without using cuda?

**Comment by kaushaltrivedi** [comment]
Hi I have not tested the model training on cpu.  The inference will work however model training is not yet supported.

**Comment by rdpulgar** [comment]
Hi, I wondering if you found a work around solution to test fast-best model training on cpu. Still getting the "cuda" crash. Thank you
