### ISSUE TITLE
Could the lamb optimizer be used in ImageNet classification?

### ISSUE THREAD

**Issue by iamweiweishi** [kaushaltrivedi/fast-bert#43]
Thank you for your contribution.
Like the paper said, the lamb optimizer could also be used for ImageNet classification. I am trying to incorporate the lamb here to my own code. Could the optimizer you contributed here be also applied in this kind of classification? 
Many thanks.

**Comment by kaushaltrivedi** [comment]
it certainly can. all you have to do is use the lamb optimiser in your training loop.  As this is not a vision library, I would start with fast.ai and change its optimiser to lamb.
