### ISSUE TITLE
unresolved problem

### ISSUE THREAD

**Issue by HamzaouiMounir** [kaushaltrivedi/fast-bert#46]
/usr/local/lib/python3.6/dist-packages/fast_bert/learner_cls.py in fit(self, epochs, lr, validate, schedule_type, optimizer_type)
    211     def fit(self, epochs, lr, validate=True, schedule_type="warmup_cosine", optimizer_type='lamb'):
    212 
--> 213         tensorboard_dir = self.output_dir/'tensorboard'
    214         tensorboard_dir.mkdir(exist_ok=True)
    215         print(tensorboard_dir)

TypeError: unsupported operand type(s) for /: 'str' and 'str

**Comment by kaushaltrivedi** [comment]
You have passed string to the output_dir parameter. Wrap that around Path object. The function expects a Path object.
