### ISSUE TITLE
More than 6 multi-labels possible?

### ISSUE THREAD

**Issue by irdeen** [kaushaltrivedi/fast-bert#47]
I'm trying to train fast-bert on a custom multi-labeled dataset (10 labels). It works perfectly when I strip down my dataset to only use 6 labels (same number as the provided toxic comments dataset), but when I try to switch the labels to be more or less than that, I get the following error:

```
Traceback (most recent call last):
File "multilabel.py", line 149, in <module> learner.fit(args.num_train_epochs, args.learning_rate, validate=True)
File "/home/ubuntu/miniconda3/lib/python3.7/site-packages/fast_bert/learner_cls.py", line 271, in fit outputs = self.model(**inputs)
File "/home/ubuntu/miniconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 547, in __call__ result = self.forward(*input, **kwargs)
File "/home/ubuntu/miniconda3/lib/python3.7/site-packages/fast_bert/modeling.py", line 194, in forward loss = loss_fct(logits.view(-1, self.num_labels), labels.view(-1, self.num_labels))
RuntimeError: shape '[-1, 10]' is invalid for input of size 36
```

Seems like fast-bert is hard-coded to strictly work for only 6 multi-labels. Especially considering I get these different errors when I change the batch size as following with 10 labels in my dataset:

batch_size = 2 --> `RuntimeError: shape '[-1, 10]' is invalid for input of size 12`
(2 batch_size * 6 (labels?) = 12?)

batch_size = 4 --> `RuntimeError: shape '[-1, 10]' is invalid for input of size 24`
(4 batch_size * 6 (labels?) = 24?)

batch_size = 6 --> `RuntimeError: shape '[-1, 10]' is invalid for input of size 36`
(6 batch_size * 6 (labels?) = 36?)

batch_size = 8 --> `RuntimeError: shape '[-1, 10]' is invalid for input of size 48`
(8 batch_size * 6 (labels?) = 48?)

Any ideas how I can solve fast-bert to use more than 6 labels?

**Comment by kaushaltrivedi** [comment]
I can confirm that 6 labels is not hardcoded. I have trained models with lot more labels for multilabel. Is it possible to share a snipet of your data. (Probably a couple of rows).

**Comment by irdeen** [comment]
That's relieving to hear! In that case it has to be a setting I've missed to fix. I wonder what. Here's a snippet 3 rows from my data:

`id,comment_text,API662,document_description,earthing_bosses,earthing_connection,fireproofing,drying,document_delivery,drip_tray,hydrotest,scheduling`
120,Design Seismic Spectrum Calculations (per EC-8) Equipment Tag Number,0,1,0,0,0,0,0,0,0,0
121,PMI - 100% Project Specification HS84218-00-PIP-SPE-0007-,0,0,0,0,0,1,0,0,0,0
122,Hydrostatic Test Approved Hydrostatic Test Procedure HS84218-,0,0,0,0,0,0,0,0,1,0`

**Comment by kaushaltrivedi** [comment]
<img width="1239" alt="Screenshot 2019-08-30 at 10 23 02" src="https://user-images.githubusercontent.com/3465437/64009785-68391f00-cb10-11e9-8e35-009107873722.png">

Just formatting, is this how your data looks like?

I am assuming your labels are 

API662
document_description
earthing_bosses
earthing_connection
fireproofing
drying
document_delivery
drip_tray
hydrotest
scheduling

Check couple of things:

[labels.csv.zip](https://github.com/kaushaltrivedi/fast-bert/files/3559278/labels.csv.zip)

1. The labels.csv file should look like the file I have attached.(not zipped off course)
2. while creating databunch you need to pass a list of your labels to label_col parameter.

**Comment by irdeen** [comment]
Found the problem! I had to delete the cache folder at `fast-bert/sample_data/multi_label_toxic_comments/data/cache`. Seems like the fast-bert didn't follow up when I updated the dataset.

Highly appreciated your help though!
