### ISSUE TITLE
error at learner.fit while running the new-toxic-multilable sample notebook

### ISSUE THREAD

**Issue by pradeepthiyyagura** [kaushaltrivedi/fast-bert#49]
learner.fit(args.num_train_epochs, args.learning_rate, validate=True)

RuntimeError                              Traceback (most recent call last)
<ipython-input-19-dbbd575bee7f> in <module>
----> 1 learner.fit(args.num_train_epochs, args.learning_rate, validate=True)

~/.conda/envs/fastbert/lib/python3.6/site-packages/fast_bert/learner_cls.py in fit(self, epochs, lr, validate, schedule_type, optimizer_type)
    311             # Evaluate the model after every epoch
    312             if validate:
--> 313                 results = self.validate()
    314                 for key, value in results.items():
    315                     self.logger.info("eval_{} after epoch {}: {}: ".format(key, (epoch + 1), value))

~/.conda/envs/fastbert/lib/python3.6/site-packages/fast_bert/learner_cls.py in validate(self)
    382         # Evaluation metrics
    383         for metric in self.metrics:
--> 384             validation_scores[metric['name']] = metric['function'](all_logits, all_labels)
    385 
    386         results = {'loss': eval_loss }

~/.conda/envs/fastbert/lib/python3.6/site-packages/fast_bert/metrics.py in accuracy_thresh(y_pred, y_true, thresh, sigmoid)
     29     if sigmoid:
     30         y_pred = y_pred.sigmoid()
---> 31     return ((y_pred > thresh) == y_true.byte()).float().mean().item()
     32 #     return np.mean(((y_pred>thresh)==y_true.byte()).float().cpu().numpy(), axis=1).sum()
     33 

~/.conda/envs/fastbert/lib/python3.6/site-packages/apex/amp/wrap.py in wrapper(*args, **kwargs)
     51 
     52         if len(types) <= 1:
---> 53             return orig_fn(*args, **kwargs)
     54         elif len(types) == 2 and types == set(['HalfTensor', 'FloatTensor']):
     55             new_args = utils.casted_args(cast_fn,

RuntimeError: Expected object of scalar type Bool but got scalar type Byte for argument #2 'other'

**Comment by kaushaltrivedi** [comment]
Hi I noticed this yesterday. I have fixed it in the master repo. So if you install from source this will work fine. Else just wait till I update pypi’s version.

**Comment by pradeepthiyyagura** [comment]
I have installed from the master repo and now have the following error
AttributeError: 'XLNetForMultiLabelSequenceClassification' object has no attribute 'transformer'


AttributeError                            Traceback (most recent call last)
<ipython-input-19-dbbd575bee7f> in <module>
----> 1 learner.fit(args.num_train_epochs, args.learning_rate, validate=True)

~/.conda/envs/fastbert_v1/lib/python3.7/site-packages/fast_bert/learner_cls.py in fit(self, epochs, lr, validate, schedule_type, optimizer_type)
    284                     inputs['token_type_ids'] = batch[2]
    285 
--> 286                 outputs = self.model(**inputs)
    287                 loss = outputs[0]  # model outputs are always tuple in pytorch-transformers (see doc)
    288 

~/.conda/envs/fastbert_v1/lib/python3.7/site-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    545             result = self._slow_forward(*input, **kwargs)
    546         else:
--> 547             result = self.forward(*input, **kwargs)
    548         for hook in self._forward_hooks.values():
    549             hook_result = hook(self, input, result)

~/.conda/envs/fastbert_v1/lib/python3.7/site-packages/fast_bert/modeling.py in forward(self, input_ids, token_type_ids, input_mask, attention_mask, mems, perm_mask, target_mapping, labels, head_mask)
    208                 mems=None, perm_mask=None, target_mapping=None,
    209                 labels=None, head_mask=None):
--> 210         transformer_outputs = self.transformer(input_ids, token_type_ids=token_type_ids,
    211                                                input_mask=input_mask, attention_mask=attention_mask,
    212                                                mems=mems, perm_mask=perm_mask, target_mapping=target_mapping,

~/.conda/envs/fastbert_v1/lib/python3.7/site-packages/torch/nn/modules/module.py in __getattr__(self, name)
    589                 return modules[name]
    590         raise AttributeError("'{}' object has no attribute '{}'".format(
--> 591             type(self).__name__, name))
    592 
    593     def __setattr__(self, name, value):

AttributeError: 'XLNetForMultiLabelSequenceClassification' object has no attribute 'transformer'

**Comment by hiwaveSupport** [comment]
I am also getting the same error - 'XLNetForMultiLabelSequenceClassification' object has no attribute 'transformer'. Running this on google collab notebook.

**Comment by kaushaltrivedi** [comment]
Fixed!!!
