### ISSUE TITLE
Unable to load pretrained model using BertLearner

### ISSUE THREAD

**Issue by abdul0807** [kaushaltrivedi/fast-bert#53]
Getting "TypeError: init_weights() takes 1 positional argument but 2 were given" when running the below code for any of bert, xlnet model. Please note that this code was working couple of days back.

learner = BertLearner.from_pretrained_model(
                        databunch,
                        pretrained_path='bert-base-uncased',#xlnet-large-cased, bert-base-uncased
                        metrics=metrics,
                        device=device_cuda,
                        logger=logger,
                        output_dir=OUTPUT_DIR,
                        finetuned_wgts_path=None,
                        warmup_steps=500,
                        multi_gpu=True,
                        is_fp16=True,
                        multi_label=True,
                        logging_steps=50)

**Comment by pydn** [comment]
I'm having the same problem.

**Comment by kaushaltrivedi** [comment]
hi can you try installing it again.  check if you have the latest version of pytorch_transformers installed.

**Comment by kaushaltrivedi** [comment]
fixed in 1.3.1.
