### ISSUE TITLE
Inference on CPU crashes

### ISSUE THREAD

**Issue by MaartenBloemen** [kaushaltrivedi/fast-bert#56]
I'm unable to load a trained model for inference on my Mac which doesn't have an Nvidia GPU.
I think it is because of [this line](https://github.com/kaushaltrivedi/fast-bert/blob/master/fast_bert/learner_cls.py#L85). It should have a check around it to make sure CUDA is available before being called.

**Comment by kaushaltrivedi** [comment]
oops.  I need to add some tests :) Will be fixed shortly.

**Comment by kaushaltrivedi** [comment]
Fixed!!!
