### ISSUE TITLE
TypeError: unsupported operand type(s) for /: 'str' and 'str'

### ISSUE THREAD

**Issue by boqrat** [kaushaltrivedi/fast-bert#62]
Hi,
I'm getting
TypeError: unsupported operand type(s) for /: 'str' and 'str'
error when calling BertDataBunch function. I'm actually surprised how it works for others because in line 294 of data_cls.py there is divide symbol between two strings:

 292         self.tokenizer = tokenizer
    293         self.data_dir = data_dir
--> 294         self.cache_dir = data_dir/'cache'
    295         self.max_seq_length = max_seq_length
    296         self.batch_size_per_gpu = batch_size_per_gpu
Thanks!

**Comment by kaushaltrivedi** [comment]
Pass a Path object instead of a string.

**Comment by kaushaltrivedi** [comment]
I have updated the code so that it will also accept string instead of Path.
