### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'max_grad_norm'

### ISSUE THREAD

**Issue by JohannesJL** [kaushaltrivedi/fast-bert#63]
Hi

I have an issue when running 
learner.fit(epochs=6,
            lr=6e-5,
            validate=True, # Evaluate the model after each epoch
            schedule_type="warmup_linear")

using the following learner object: 

logger = logging.getLogger()
device_cuda = torch.device("cuda")
metrics = [{'name': 'accuracy', 'function': accuracy}]

learner = BertLearner.from_pretrained_model(
    databunch,
    pretrained_path='bert-base-uncased',
    metrics=metrics,
    device=device_cuda,
    logger=logger,
    #output_dir=OUTPUT_DIR,
    finetuned_wgts_path=None,
    #warmup_steps=500,
    multi_gpu=True,
    is_fp16=True,
    multi_label=False, 
    max_grad_norm=1.0)

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-21-a0ba498dd0ca> in <module>
      2             lr=6e-5,
      3             validate=True, # Evaluate the model after each epoch
----> 4             schedule_type="warmup_linear")

~/.conda/envs/transformers/lib/python3.7/site-packages/fast_bert/learner.py in fit(self, epochs, lr, validate, schedule_type)
    462 
    463         if self.use_amp_optimizer == False:
--> 464             self.fit_old(epochs, lr, validate=validate, schedule_type=schedule_type)
    465             return
    466 

~/.conda/envs/transformers/lib/python3.7/site-packages/fast_bert/learner.py in fit_old(self, epochs, lr, validate, schedule_type)
    573         num_train_steps = int(len(self.data.train_dl) / self.grad_accumulation_steps * epochs)
    574         if self.optimizer is None:
--> 575             self.optimizer, self.schedule = self.get_optimizer_old(lr , num_train_steps)
    576 
    577         t_total = num_train_steps

~/.conda/envs/transformers/lib/python3.7/site-packages/fast_bert/learner.py in get_optimizer_old(self, lr, num_train_steps, schedule_type)
    233                                   lr=lr,
    234                                   bias_correction=False,
--> 235                                   max_grad_norm=1.0)
    236 
    237             if self.loss_scale == 0:

TypeError: __init__() got an unexpected keyword argument 'max_grad_norm'

Does anyone know how to fix? 
Thanks!

**Comment by kaushaltrivedi** [comment]
hello it seems you are using the old learner.  use the new learner_cls file. everything else remains the same.

**Comment by JohannesJL** [comment]
Thank you, issue resolved.
And  thanks a lot for the great work!
