### ISSUE TITLE
Saving bin file from learner and then load it

### ISSUE THREAD

**Issue by ahmedbahaaeldin** [kaushaltrivedi/fast-bert#9]
I used learner.save_and_reload to save my model and an output of pretrained_bert.bin occured. How can i used this .bin file and classify with learner.predict_batches() as i have been stuck for ages and i dont know how.

**Comment by Pawel-Kranzberg** [comment]
This worked for me:
`BERT_PRETRAINED_PATH = 'bert-base-uncased'
MODEL_PATH=Path('./models/')
...
learner.save_and_reload(MODEL_PATH, 'jigsaw_toxic_FastBert_model_v01')

predictor = BertClassificationPredictor(model_path = './models/jigsaw_toxic_FastBert_model_v01.bin', pretrained_path = BERT_PRETRAINED_PATH,
                                        label_path=LABEL_PATH, multi_gpu = multi_gpu, multi_label = True)

# Single prediction
single_prediction = predictor.predict("just get me result for this friggin fugly text")
print(single_prediction)`
