### ISSUE TITLE
Getting AttributeError Error when I call fit function for training. Please help!

### ISSUE THREAD

**Issue by Nomiluks** [kaushaltrivedi/fast-bert#93]
**Code**
`learner.fit(args.num_train_epochs, args.learning_rate, validate=True)`

**Error:**

> drive/My Drive/BERT-MultiLabel Text Classification/models/output/tensorboard
> Selected optimization level O1:  Insert automatic casts around Pytorch functions and Tensor methods.
> 
> Defaults for this optimization level are:
> enabled                : True
> opt_level              : O1
> cast_model_type        : None
> patch_torch_functions  : True
> keep_batchnorm_fp32    : None
> master_weights         : None
> loss_scale             : dynamic
> Processing user overrides (additional kwargs that are not None)...
> After processing overrides, optimization options are:
> enabled                : True
> opt_level              : O1
> cast_model_type        : None
> patch_torch_functions  : True
> keep_batchnorm_fp32    : None
> master_weights         : None
> loss_scale             : dynamic
> 10/19/2019 10:43:20 - INFO - numexpr.utils -   NumExpr defaulting to 2 threads.
> ---------------------------------------------------------------------------
> AttributeError                            Traceback (most recent call last)
> <ipython-input-25-dbbd575bee7f> in <module>()
> ----> 1 learner.fit(args.num_train_epochs, args.learning_rate, validate=True)
> 
> 5 frames
> /usr/local/lib/python3.6/dist-packages/fast_bert/learner_cls.py in fit(self, epochs, lr, validate, schedule_type, optimizer_type)
>     185 
>     186         # Get scheduler
> --> 187         scheduler = self.get_scheduler(optimizer, t_total=t_total, schedule_type=schedule_type)
>     188 
>     189         # Parallelize the model architecture
> 
> /usr/local/lib/python3.6/dist-packages/fast_bert/learner_util.py in get_scheduler(self, optimizer, t_total, schedule_type)
>      76         }
>      77 
> ---> 78         return SCHEDULES[schedule_type](optimizer, warmup_steps=self.warmup_steps, t_total=t_total)
>      79 
>      80     def save_model(self):
> 
> /usr/local/lib/python3.6/dist-packages/transformers/optimization.py in __init__(self, optimizer, warmup_steps, t_total, cycles, last_epoch)
>      72         self.t_total = t_total
>      73         self.cycles = cycles
> ---> 74         super(WarmupCosineSchedule, self).__init__(optimizer, self.lr_lambda, last_epoch=last_epoch)
>      75 
>      76     def lr_lambda(self, step):
> 
> /usr/local/lib/python3.6/dist-packages/torch/optim/lr_scheduler.py in __init__(self, optimizer, lr_lambda, last_epoch)
>     140             self.lr_lambdas = list(lr_lambda)
>     141         self.last_epoch = last_epoch
> --> 142         super(LambdaLR, self).__init__(optimizer, last_epoch)
>     143 
>     144     def state_dict(self):
> 
> /usr/local/lib/python3.6/dist-packages/torch/optim/lr_scheduler.py in __init__(self, optimizer, last_epoch)
>      56             return wrapper
>      57 
> ---> 58         self.optimizer.step = with_counter(self.optimizer.step)
>      59         self.optimizer._step_count = 0
>      60         self._step_count = 0
> 
> /usr/local/lib/python3.6/dist-packages/torch/optim/lr_scheduler.py in with_counter(method)
>      38             # Keep a weak reference to the optimizer instance to prevent
>      39             # cyclic references.
> ---> 40             instance_ref = weakref.ref(method.__self__)
>      41             # Get the unbound method for the same purpose.
>      42             func = method.__func__
> 
> AttributeError: 'function' object has no attribute '__self__'
<img width="902" alt="Error" src="https://user-images.githubusercontent.com/4704211/67144520-a80ac000-f290-11e9-8b92-23dd9d37b8d6.png">

**Comment by kaushaltrivedi** [comment]
please update both Apex and transformers packages and try again. I was able to run this yesterday successfully.

**Comment by Nomiluks** [comment]
> please update both Apex and transformers packages and try again. I was able to run this yesterday successfully.

Okay let m

**Comment by Nomiluks** [comment]
Thanks it worked for me!
