### ISSUE TITLE
ParserError: Error tokenizing data. C error: Expected 8 fields in line 7, saw 11

### ISSUE THREAD

**Issue by C24IO** [kaushaltrivedi/fast-bert#96]
https://github.com/kaushaltrivedi/fast-bert/blob/f373898f40ea89af0d287cc671cc6337c4ddb23e/sample_notebooks/new-toxic-multilabel.ipynb#L367

`10/21/2019 18:02:01 - INFO - transformers.file_utils -   https://s3.amazonaws.com/models.huggingface.co/bert/xlnet-base-cased-spiece.model not found in cache or force_download set to True, downloading to /tmp/tmphj2mdgyi
100%|██████████| 798011/798011 [00:00<00:00, 1909194.62B/s]
10/21/2019 18:02:02 - INFO - transformers.file_utils -   copying /tmp/tmphj2mdgyi to cache at /home/ec2-user/.cache/torch/transformers/dad589d582573df0293448af5109cb6981ca77239ed314e15ca63b7b8a318ddd.8b10bd978b5d01c21303cc761fc9ecd464419b3bf921864a355ba807cfbfafa8
10/21/2019 18:02:02 - INFO - transformers.file_utils -   creating metadata file for /home/ec2-user/.cache/torch/transformers/dad589d582573df0293448af5109cb6981ca77239ed314e15ca63b7b8a318ddd.8b10bd978b5d01c21303cc761fc9ecd464419b3bf921864a355ba807cfbfafa8
10/21/2019 18:02:02 - INFO - transformers.file_utils -   removing temp file /tmp/tmphj2mdgyi
10/21/2019 18:02:02 - INFO - transformers.tokenization_utils -   loading file https://s3.amazonaws.com/models.huggingface.co/bert/xlnet-base-cased-spiece.model from cache at /home/ec2-user/.cache/torch/transformers/dad589d582573df0293448af5109cb6981ca77239ed314e15ca63b7b8a318ddd.8b10bd978b5d01c21303cc761fc9ecd464419b3bf921864a355ba807cfbfafa8

10/21/2019 18:02:02 - INFO - root -   Loading features from cached file ../data/cache/cached_xlnet_train_multi_label_512
/home/ec2-user/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2963: DtypeWarning: Columns (1,2,3,4,5,6) have mixed types. Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)
---------------------------------------------------------------------------
ParserError                               Traceback (most recent call last)
<ipython-input-25-7677b699a1bb> in <module>()
      3                           text_col="comment_text", label_col=label_cols,
      4                           batch_size_per_gpu=args['train_batch_size'], max_seq_length=args['max_seq_length'],
----> 5                           multi_gpu=args.multi_gpu, multi_label=True, model_type=args.model_type)

~/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/fast_bert/data_cls.py in __init__(self, data_dir, label_dir, tokenizer, train_file, val_file, test_data, label_file, text_col, label_col, batch_size_per_gpu, max_seq_length, multi_gpu, multi_label, backend, model_type, logger, clear_cache, no_cache)
    366             if os.path.exists(cached_features_file) == False:
    367                 val_examples = processor.get_dev_examples(
--> 368                     val_file, text_col=text_col, label_col=label_col)
    369 
    370             val_dataset = self.get_dataset_from_examples(val_examples, 'dev')

~/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/fast_bert/data_cls.py in get_dev_examples(self, filename, text_col, label_col, size)
    235 
    236         if size == -1:
--> 237             data_df = pd.read_csv(os.path.join(self.data_dir, filename))
    238             return self._create_examples(data_df, "dev", text_col=text_col, label_col=label_col)
    239         else:

~/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/pandas/io/parsers.py in parser_f(filepath_or_buffer, sep, delimiter, header, names, index_col, usecols, squeeze, prefix, mangle_dupe_cols, dtype, engine, converters, true_values, false_values, skipinitialspace, skiprows, skipfooter, nrows, na_values, keep_default_na, na_filter, verbose, skip_blank_lines, parse_dates, infer_datetime_format, keep_date_col, date_parser, dayfirst, iterator, chunksize, compression, thousands, decimal, lineterminator, quotechar, quoting, doublequote, escapechar, comment, encoding, dialect, tupleize_cols, error_bad_lines, warn_bad_lines, delim_whitespace, low_memory, memory_map, float_precision)
    700                     skip_blank_lines=skip_blank_lines)
    701 
--> 702         return _read(filepath_or_buffer, kwds)
    703 
    704     parser_f.__name__ = name

~/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/pandas/io/parsers.py in _read(filepath_or_buffer, kwds)
    433 
    434     try:
--> 435         data = parser.read(nrows)
    436     finally:
    437         parser.close()

~/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/pandas/io/parsers.py in read(self, nrows)
   1137     def read(self, nrows=None):
   1138         nrows = _validate_integer('nrows', nrows)
-> 1139         ret = self._engine.read(nrows)
   1140 
   1141         # May alter columns / col_dict

~/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/pandas/io/parsers.py in read(self, nrows)
   1993     def read(self, nrows=None):
   1994         try:
-> 1995             data = self._reader.read(nrows)
   1996         except StopIteration:
   1997             if self._first_chunk:

pandas/_libs/parsers.pyx in pandas._libs.parsers.TextReader.read()

pandas/_libs/parsers.pyx in pandas._libs.parsers.TextReader._read_low_memory()

pandas/_libs/parsers.pyx in pandas._libs.parsers.TextReader._read_rows()

pandas/_libs/parsers.pyx in pandas._libs.parsers.TextReader._tokenize_rows()

pandas/_libs/parsers.pyx in pandas._libs.parsers.raise_parser_error()

ParserError: Error tokenizing data. C error: Expected 8 fields in line 7, saw 11`

**Comment by mauryaland** [comment]
It seems that your file has a formatting problem. You should check line 7 of your file to check if there is any inconstancy. If not, it could be due to quote breaking the format. What you can try is modifying locally the line 237 of the data_cls.py module from fast-bert library as follow:
```python
data_df = pd.read_csv(os.path.join(self.data_dir, filename), quoting=3)
```

Sometimes, using the python engine could also fix the issue:
```python
data_df = pd.read_csv(os.path.join(self.data_dir, filename), engine='python')
```

Last but not least, if none of these solutions fix the issue, you could just set error_bad_lines to false in order to skip the bad line: 
```python
data_df = pd.read_csv(os.path.join(self.data_dir, filename), error_bad_lines=False)
```

Hope it can help!

**Comment by C24IO** [comment]
Thanks @mauryaland that was helpful. It was my bad in the end, the val.csv file was mangled. Marking this resolved.
