### ISSUE TITLE
Question: lm_train.txt and lm_val.txt examples

### ISSUE THREAD

**Issue by CMobley7** [kaushaltrivedi/fast-bert#98]
If possible, can you add the appropriate format for lm_train.txt and lm_val.txt in the README or add an example to sample_data directory?

**Comment by ramakth1** [comment]
any update on the data?

**Comment by CMobley7** [comment]
An example is the `raw character level data` found [here](https://blog.einstein.ai/the-wikitext-long-term-dependency-language-modeling-dataset/) for WikiText.
